Mention recursion as an attack vector
ietf-wg-jsonpath/draft-ietf-jsonpath-base pull request #197
Opened 2022-06-17 14:39 UTC by glyn

Also add some general advice from https://www.rfc-editor.org/rfc/rfc8949#name-security-considerations.

Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/186#issuecomment-1158920404

2022-06-17 15:19 UTC, timbray approved these changes

2022-06-17 16:10 UTC, cabo requested changes

2022-06-17 16:42 UTC, glyn commented on draft-ietf-jsonpath-base.md
> +exponential, CPU usage or, for example via the descendant selector,
That example points out the main source of recursion in JSONPath implementations and will hopefully make implementers think twice about how they implement this feature.

(The other potential source of recursion would be nested filters, but our grammar currently precludes these.)

2022-06-24 16:03 UTC, timbray commented on draft-ietf-jsonpath-base.md
> +exponential, CPU usage or, for example via the descendant selector,
I think the descendent-selector mention is OK, probably adds value.  But maybe find a way to use the word "recursion"?

2022-06-24 16:24 UTC, cabo commented
On 24. Jun 2022, at 18:03, Tim Bray ***@***.***> wrote:
> 
> But maybe find a way to use the word "recursion”?

Recursion is not really the problem, stack depth is (or any other uncontrolled resource usage triggered by queries into deeply nested structures).

Grüße, Carsten

2022-06-24 17:09 UTC, glyn commented
@cabo Are you comfortable with this now, or would you perhaps like to suggest some other way to address the concerns of https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/186?

2022-06-25 22:25 UTC, cabo commented on draft-ietf-jsonpath-base.md
> +exponential, CPU usage or, for example via the descendant selector,
```suggestion
exponential, CPU usage or, for example via a naive recursive implementation for the descendant selector,
```

2022-06-26 02:51 UTC, glyn commented on draft-ietf-jsonpath-base.md
> +exponential, CPU usage or, for example via the descendant selector,
@cabo Applied the change, thanks. Please could you approve the PR?

2022-07-12 20:14 UTC, cabo approved these changes
Thank you.

2022-07-13 09:45 UTC, merged