NodesType functions are not directly comparable
ietf-wg-jsonpath/draft-ietf-jsonpath-base pull request #429
Opened 2023-03-14 21:20 UTC by glyn

Thanks to @gregsdennis for spotting this.

2023-03-14 21:39 UTC, gregsdennis requested changes

2023-03-14 21:39 UTC, gregsdennis commented on draft-ietf-jsonpath-base.md
> -  `NodesType`.
I think this change was meant for below.  `NodesType` is still valid for test expressions.  The line below is about comparisons.

2023-03-14 22:05 UTC, gregsdennis approved these changes

2023-03-15 23:53 UTC, glyn commented
@cabo I presume you are ok with this change, so I'm going to merge it. Any concern, let me know and we can adjust the result.

2023-03-15 23:53 UTC, merged

2023-03-16 00:56 UTC, cabo commented
> @cabo I presume you are ok with this change, so I'm going to merge it. 

Yes. Just didn't have chance to check this in context, but if I remember this properly, this change is good (and necessary).