character-repertoire issues
ietf-wg-jsonpath/draft-ietf-jsonpath-base pull request #512
Opened 2023-09-21 16:28 UTC by timbray

2023-09-21 16:46 UTC, cabo requested changes
Looks good, except for the attempt to get rid of the ugly JSON escapes.

2023-09-21 16:46 UTC, cabo commented on draft-ietf-jsonpath-base.md
> +Unicode scalar valuess as described
```suggestion
Unicode scalar values as described
```

2023-09-21 16:46 UTC, cabo commented on draft-ietf-jsonpath-base.md
> +Note that the "\u" Unicode character escape is dissimilar from the
No, that is not the way we have defined JSONPath to be.
(Even if we wanted to change this now, \u1F609 is ambiguous (U+1f60 + character 9?), so we'd need to adopt one of the syntaxes \U or \u{}...)

2023-09-21 19:48 UTC, cabo approved these changes
(Ignoring the change to lib) these changes now look good.  They do show the tedium of skipping the surrogate code points in each ABNF range covering that space, but that may be the best minimum change we can do here.

2023-09-21 21:23 UTC, cabo commented
> What's the outcome of this change? 

Over on the jsonpath mailing list, I wrote:

> > The recent extensive discussions on [art@ietf.org](mailto:art@ietf.org) and [i18n@ietf.org](mailto:i18n@ietf.org) have heightened our senses for potential misunderstandings of the way JSONPath handles Unicode.  Pull request 512 [1] is intended to address this.
> >
> > Note that while this PR occurs during IESG processing, this is not based on an IESG comment.
Some of us still would like to make this change before the document is approved.
> >
> > These changes are editorial in nature in that the technical content does not change, it is just expressed in a way that may give less opportunities for confusion.  
> >
> > So I’m requesting that the WG please have a look and speak up if you see a problem with this editorial improvement.

I think that should answer your question.

> Is it that surrogate pairs are no longer to be supported? 

There is no technical change here; JSONPath parsers never see surrogate pairs; these happen only inside UTF-16.
The ABNF changes make it more obvious that lone surrogate code points cannot occur in a JSONPath query; that is already the case now (see Section 1.1 in conjunction with RFC 3269).

> What's the reasoning?
> 
> Providing some context in the description on PRs would be good.

Sorry for putting this in the WG message only; the background is some extensive discussion on art@ and i18n@ that we don't want to repeat here in the JSONPath WG.

2023-09-21 21:28 UTC, gregsdennis commented
> I think that should answer your question.

No, that doesn't answer my question.  I saw that email and still asked.

> the background is some extensive discussion on art@ and i18n@ that we don't want to repeat here in the JSONPath WG.

Because I'm not subscribed to those, is there a summary?

2023-09-21 22:58 UTC, timbray commented
Basically, the JSONPath draft has always said that the character
repertoire for JSONPath is “Unicode scalar values”, which is all the code
points except surrogates, which only have meaning in UTF-16.  The recent
changes did a few s/code point/scalar value/ and changed one piece of ABNF
to make it clear that surrogates are not supported.

On Sep 21, 2023 at 2:28:44 PM, Greg Dennis ***@***.***> wrote:

> I think that should answer your question.
>
> No, that doesn't answer my question. I saw that email and still asked.
>
> the background is some extensive discussion on art@ and i18n@ that we
> don't want to repeat here in the JSONPath WG.
>
> Because I'm not subscribed to those, is there a summary?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/512#issuecomment-1730327489>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAEJEYKUHEUR3SO57OQY5DX3SWQZANCNFSM6AAAAAA5B2I4YM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-09-22 02:25 UTC, gregsdennis commented
Thank you

2023-09-22 07:11 UTC, glyn approved these changes
LGTM, once the lib changes are reverted.

2023-09-24 05:23 UTC, cabo commented on sourcecode/abnf/jsonpath_collected_abnf
> +                      %x7E-D7FF /   ; skip surrogate code points
Oops.  This should be %x80, not %x7E (~ is not a good name character).

2023-09-24 05:24 UTC, cabo commented on draft-ietf-jsonpath-base.md
> +                      %x7E-D7FF /   ; skip surrogate code points
(See above0

2023-09-24 15:56 UTC, glyn approved these changes
@cabo Thanks for fixing the typo! I was just about to dig into it...

2023-09-24 16:27 UTC, merged